// Shared trip data — surfaces the same content across all 3 design directions
window.TRIP = {
  meta: {
    code: 'POLSKA',
    edition: '2026 Poland Field Plan',
    dateRange: '2026 / 10 / 24 — 10 / 31',
    tripStart: '2026-10-24',
    tripEnd: '2026-10-31',
    timeZone: 'Europe/Warsaw',
    nights: 7, days: 8,
    cities: ['Warszawa', 'Kraków', 'Wrocław', 'Poznań'],
    route: '華沙 → 克拉科夫 → 樂斯拉夫 → 波茲南 → 華沙',
    style: '高效率城市探索 · 腳程快 · 重點景點完整走完',
    highestRiskDays: ['Day 5 樂斯拉夫全景點 + 晚轉場', 'Day 7 三館連看'],
    flights: '國泰 + 卡達 + 長榮聯運',
  },
  days: [
    {
      n: 1, date: '10/24 (六)', city: '華沙',
      title: '抵達華沙 · 老城傍晚漫步',
      headline: '13:30 抵蕭邦機場，SKM 進城，老城散步、倒時差',
      tag: 'Arrival',
      intensity: '低',
      hardConstraints: ['不排室內博物館', '晚上早睡，保留 Day 2 轉場體力'],
      mustBook: [],
      compressible: ['老城散步範圍', '晚餐後甜點'],
      weather: '11° / 6°',
      steps: [
        {t:'13:30', label:'抵蕭邦機場', sub:'申根入境 + 提行李 ~75min', cost:'—', dur:'75 min'},
        {t:'14:45', label:'SKM S2/S3', sub:'4.4 PLN · 20 min 進城', cost:'PLN 4.4', dur:'20 min'},
        {t:'15:15', label:'旅館 Check-in', dur:'30 min'},
        {t:'16:45', label:'★ 老城廣場', sub:'皇家城堡 · 美人魚雕像', cost:'免費', dur:'1 h'},
        {t:'18:00', label:'Krakowskie Przedmieście', sub:'黃昏氛圍', cost:'免費', dur:'1 h'},
        {t:'19:00', label:'Pierogi 晚餐', sub:'Zapiecek · Podwale 19', cost:'PLN 35–55'},
        {t:'21:00', label:'早睡倒時差'},
      ],
      eat: ['Pierogi @ Zapiecek', 'Wedel 熱巧克力 @ E. Wedel Pijalnia'],
      backup: [
        {label:'下雨備案', where:'科學文化宮 30F 觀景台', why:'PLN 25 · 室內 + 360° 城景，老城廣場走路 12 分'},
        {label:'時差太累', where:'Łazienki 公園溫室', why:'室內展館 + 蕭邦像，免費，傍晚前可走'},
      ],
      practical: [
        {tag:'寄物', name:'Warszawa Centralna', note:'地下層自助 locker · PLN 8/12 大小箱'},
        {tag:'換錢', name:'Internet Kantor (Marszałkowska)', note:'四城最佳匯率，價差 ≤ 1%'},
        {tag:'SIM', name:'Play / Plus / Orange', note:'機場到達層櫃台，PLN 30 起 30 天無限'},
      ],
    },
    {
      n: 2, date: '10/25 (日)', city: '華沙 → 克拉科夫',
      title: 'Wawel + 老城 + 辛德勒最後入場 + Kazimierz 晚餐',
      headline: 'EIP Pendolino 09:00 → 11:25 · 頭等艙含早餐',
      tag: 'Transit',
      intensity: '高',
      hardConstraints: ['09:00 華沙 → 克拉科夫火車', '辛德勒工廠 17:30 最後入場', '午餐與 Check-in 不能拖太久'],
      mustBook: ['華沙 → 克拉科夫火車', '辛德勒工廠 17:30 時段票'],
      compressible: ['聖瑪利亞教堂內部參觀', '紡織會館購物時間'],
      weather: '12° / 5°',
      train: {type:'EIP', from:'WAW', to:'KRK', dep:'09:00', arr:'11:25', dur:'2h25', price:'PLN 130–180'},
      steps: [
        {t:'09:00', label:'EIP Pendolino 出發', sub:'頭等艙 · Wi-Fi · 早餐', cost:'PLN 130–180', dur:'2h25'},
        {t:'11:25', label:'抵 Kraków Główny', dur:'10 min 拖行李'},
        {t:'13:00', label:'★ 瓦維爾大教堂', sub:'週日 12:30–17:00', cost:'PLN 26', dur:'45 min'},
        {t:'14:00', label:'★ Wawel 國家廳室', sub:'最後入場 15:10 ⚠', cost:'PLN 45–65', dur:'1.5 h'},
        {t:'16:00', label:'★ 中央廣場 + 聖瑪利亞', sub:'整點 Hejnał 號角', cost:'PLN 20 (登塔)', dur:'45 min'},
        {t:'16:45', label:'紡織會館 Sukiennice 快速一覽', sub:'採購留到 10/27', cost:'免費入場', dur:'15 min'},
        {t:'17:00', label:'電車 50 / 24 到 Plac Bohaterów Getta', dur:'15 min'},
        {t:'17:30', label:'★ 辛德勒工廠最後入場', sub:'週日 last entry 17:30 · mhk.pl/en 預約', cost:'PLN 38', dur:'2 h'},
        {t:'19:45', label:'★ Kazimierz Plac Nowy zapiekanka 晚餐', sub:'Endzior / Krzysiek', cost:'PLN 18–25'},
      ],
      eat: ['Obwarzanek 圓圈麵包 (PGI)', 'Zapiekanka @ Plac Nowy 圓亭', 'Klezmer-Hois 猶太料理'],
      warn: '⚠️ 辛德勒 17:30 為週日最後入場時段，必須提前 1–2 週於 mhk.pl/en 線上預約該時段票（PLN 38）；另 10/25 為非營業週日（2026 全年僅 8 個營業週日，10 月無），購物中心與多數商店關閉，餐廳/藥局/Żabka 不受限——當日勿排購物',
      backup: [
        {label:'辛德勒 17:30 滿場', where:'改至下午較早時段（如 14:00），Wawel 順序往前壓', why:'mhk.pl/en 開放預約後立即下單，避免擠到最後一場'},
        {label:'雨天替代 Wawel', where:'地下市集博物館 Rynek Underground', why:'廣場下方歷史展，PLN 32，1.5h 室內'},
      ],
      practical: [
        {tag:'寄物', name:'Kraków Główny 主月台', note:'自助 locker PLN 9/15，火車站直達廣場 8 分'},
        {tag:'換錢', name:'Kantor Pomocna (廣場 14 號)', note:'廣場周邊最佳，比 Kantor.pl 便宜 0.5%'},
        {tag:'電車', name:'Wawel → Podgórze 路線', note:'廣場附近搭 50 號或 24 號電車約 15 分到 Plac Bohaterów Getta，下車即辛德勒'},
      ],
    },
    {
      n: 3, date: '10/26 (一)', city: '克拉科夫',
      title: 'Auschwitz-Birkenau · 一日往返',
      headline: '波蘭最沉重也最重要的一天',
      tag: 'Memorial',
      intensity: '中高',
      hardConstraints: ['導覽開團前 30 分鐘抵達', '晚間不再加博物館或長距離步行'],
      mustBook: ['Auschwitz 官方英文導覽'],
      compressible: ['回克拉科夫後晚餐形式', '晚間自由活動'],
      weather: '10° / 4°',
      train: {type:'BUS', from:'KRK', to:'Oświęcim', dep:'07:30', arr:'09:00', dur:'1h30 ×2', price:'PLN 15 ×2'},
      steps: [
        {t:'07:30', label:'Lajkonik 巴士', sub:'MDA D9 / D10 月台', cost:'PLN 15', dur:'1h30'},
        {t:'09:00', label:'抵 Auschwitz I', sub:'安檢、寄包、領耳機', dur:'30 min'},
        {t:'10:00', label:'★ 英文官方導覽', sub:'一館 + 比克瑙 · 3.5h', cost:'PLN 150', dur:'3.5 h'},
        {t:'13:30', label:'導覽結束'},
        {t:'14:30', label:'巴士返克拉科夫', cost:'PLN 15', dur:'1h30'},
        {t:'16:00', label:'抵 Kraków · 休息'},
        {t:'18:00', label:'安靜晚餐沉澱情緒', cost:'PLN 60–100'},
      ],
      warn: '須提前 2–3 週於 visit.auschwitz.org 預約英文官方導覽 · 開團前 30 分鐘抵達完成安檢',
      backup: [
        {label:'戶外為主 · 必備雨具', where:'比克瑙營區戶外 80%', why:'導覽風雨無阻，請穿防水鞋 + 帶折傘'},
        {label:'若無導覽額度', where:'MOCAK 當代藝術博物館 + Galicia Jewish Museum', why:'PLN 28 + PLN 25，兩館同 Podgórze 區，半天室內，主題延伸 WWII 與猶太歷史'},
      ],
    },
    {
      n: 4, date: '10/27 (二)', city: '克拉科夫 → 樂斯拉夫',
      title: 'Wieliczka 鹽礦 + Kazimierz 白天 · 傍晚轉場',
      headline: 'IC 19:30 → 22:20 · 2h50',
      tag: 'Transit',
      intensity: '高',
      hardConstraints: ['早上完成 Wieliczka 鹽礦', '18:30 前取行李並前往 Kraków Główny', '19:30 克拉科夫 → 樂斯拉夫火車'],
      mustBook: ['Wieliczka 鹽礦英文團', '克拉科夫 → 樂斯拉夫火車'],
      compressible: ['Kazimierz 白天散步', '紡織會館採購'],
      weather: '11° / 5°',
      train: {type:'IC', from:'KRK', to:'WRO', dep:'19:30', arr:'22:20', dur:'2h50', price:'PLN 60–110'},
      steps: [
        {t:'08:00', label:'早餐 + 退房', sub:'行李寄旅館'},
        {t:'09:00', label:'火車到 Wieliczka Rynek-Kopalnia', sub:'Koleje Małopolskie', cost:'PLN 4.50', dur:'25 min'},
        {t:'10:00', label:'★ Wieliczka 鹽礦 Tourist Route 英文團', sub:'3.5 km · 135m 深 · St. Kinga 鹽教堂', cost:'from PLN 131', dur:'2–3 h'},
        {t:'13:00', label:'Wieliczka 鎮中心午餐', cost:'PLN 40–60', dur:'30 min'},
        {t:'13:30', label:'火車回 Kraków Główny', cost:'PLN 4.50', dur:'25 min'},
        {t:'14:30', label:'★ Kazimierz 白天散步', sub:'舊猶太會堂 · Szeroka 街 · 《辛德勒名單》場景', cost:'免費', dur:'1.5 h'},
        {t:'16:00', label:'紡織會館 Sukiennice 採購收尾', sub:'琥珀、刺繡、Wedel 巧克力', dur:'45 min'},
        {t:'17:00', label:'自由活動或補拍照、找地方喝咖啡', sub:'19:30 車次已多出近 2 小時緩衝', dur:'1 h'},
        {t:'18:00', label:'旅館取行李 → Bolt 到 Kraków Główny', cost:'PLN 15'},
        {t:'19:30', label:'IC 火車出發', cost:'PLN 60–110', dur:'2h50'},
        {t:'22:20', label:'抵 Wrocław Główny'},
      ],
      eat: ['鹽礦 125m 地下餐廳 Karczma Górnicza', 'Sernik @ Cukiernia Michałek', 'Pierożki u Vincenta（Kazimierz）'],
      warn: '⚠️ 鹽礦英文團名額有限，必須提前 2–4 週於 wieliczka-saltmine.com 預約 10:00 場次；克拉科夫 → 樂斯拉夫此路線無 Pendolino，最晚直達車約 22:54，19:30 班次尚屬保守選擇',
      backup: [
        {label:'鹽礦客滿或超時', where:'改 11:00 / 12:00 英文場，19:30 車次仍有 2h 以上緩衝可吸收', why:'此路段最晚直達車約 22:54，19:30 出發不會卡到最後一班'},
        {label:'雨天備案', where:'鹽礦本身就在地下 135m', why:'地下約 17–18°C、防雨遮陽最佳備案'},
        {label:'想留更多 Kazimierz 時間', where:'17:00–18:00 這段可延伸散步或找地方坐下喝咖啡', why:'19:30 車次已比舊排法多出近 2 小時緩衝'},
      ],
      practical: [
        {tag:'交通', name:'Wieliczka 火車', note:'Kraków Główny S1 / R 線到 Wieliczka Rynek-Kopalnia，月台買票 PLN 4.50'},
        {tag:'寄物', name:'旅館 + Główny locker 雙層保險', note:'退房後優先寄旅館；若旅館不收，車站 locker PLN 9'},
        {tag:'裝備', name:'鹽礦低溫', note:'地下約 17–18°C，攜薄外套；官方標示全程超過 800 階，須穿好走鞋'},
      ],
    },
    {
      n: 5, date: '10/28 (三)', city: '樂斯拉夫 → 波茲南',
      title: '小矮人尋寶 + 點燈儀式 + 晚轉場',
      headline: 'IC 19:00 → 21:20 · 2h20',
      tag: 'Transit',
      intensity: '很高',
      hardConstraints: ['早餐後早出門', '百年廳距離老城較遠需抓交通', '19:00 樂斯拉夫 → 波茲南火車'],
      mustBook: ['樂斯拉夫 → 波茲南火車', '拉茨瓦維採全景畫場次'],
      compressible: ['百年廳停留縮短為外觀與周邊', '座堂島改 45–60 分鐘重點散步', '午餐改簡餐或外帶'],
      weather: '10° / 4°',
      train: {type:'IC', from:'WRO', to:'POZ', dep:'19:00', arr:'21:20', dur:'2h20', price:'PLN 50–90'},
      steps: [
        {t:'09:00', label:'★ 中央廣場 + 紡織會館', sub:'dwarfsmap.com 找小矮人', cost:'免費', dur:'1.5 h'},
        {t:'10:30', label:'糖果屋雙屋 + 教堂塔樓', sub:'91m 全景', cost:'PLN 15', dur:'45 min'},
        {t:'11:30', label:'★ 拉茨瓦維採全景畫', sub:'30 分鐘導覽', cost:'PLN 50', dur:'1 h'},
        {t:'13:30', label:'★ 百年廳 (UNESCO)', sub:'外觀 + 四穹頂展館', cost:'PLN 30', dur:'1.5 h'},
        {t:'15:50', label:'★ 座堂島煤氣燈', sub:'點燈師 102 盞 · 日落 16:32', cost:'免費', dur:'45 min'},
        {t:'19:00', label:'IC 火車出發', cost:'PLN 50–90', dur:'2h20'},
      ],
      eat: ['Śląskie kluski @ Konspira', 'Browar Stu Mostów 精釀'],
      backup: [
        {label:'雨天備案', where:'SkyTower 49F 觀景台', why:'PLN 22，212m 全城景，雨天最佳室內備案'},
        {label:'點燈師看不到', where:'廣場連拱廊 + 紡織會館內部市集', why:'若 16:32 日落雨遮蔽煤氣燈，回廣場喝熱酒（PLN 12）'},
      ],
    },
    {
      n: 6, date: '10/29 (四)', city: '波茲南 → 華沙',
      title: '山羊鐘樓秀 + 聖馬丁牛角麵包',
      headline: 'EIP 17:30 → 19:50 · 2h20',
      tag: 'Transit',
      intensity: '中高',
      hardConstraints: ['11:45 前抵達老城廣場卡位', '12:00 山羊鐘樓秀', '17:30 波茲南 → 華沙火車'],
      mustBook: ['波茲南 → 華沙火車', '牛角麵包博物館場次'],
      compressible: ['Stary Browar 停留時間', '帝王城堡內部參觀'],
      weather: '11° / 5°',
      train: {type:'EIP', from:'POZ', to:'WAW', dep:'17:30', arr:'19:50', dur:'2h20', price:'PLN 90–150'},
      steps: [
        {t:'09:00', label:'★ 教堂島 Ostrów Tumski', sub:'梅什科一世受洗地', cost:'PLN 16', dur:'1.5 h'},
        {t:'11:00', label:'廣場卡正面位置', dur:'45 min · 提早卡位'},
        {t:'12:00', label:'★ 山羊鐘樓秀', sub:'每天中午限定', cost:'免費', dur:'5 min'},
        {t:'12:15', label:'★ 聖馬丁牛角麵包 (PGI)', sub:'Cukiernia Kandulski', cost:'PLN 12–18', dur:'15 min'},
        {t:'14:00', label:'帝王城堡 / Stary Browar', cost:'PLN 16', dur:'2 h'},
        {t:'17:30', label:'EIP 出發', cost:'PLN 90–150', dur:'2h20'},
        {t:'19:50', label:'抵華沙中央車站'},
      ],
      eat: ['Rogal Świętomarciński (PGI) ⭐', 'Pyry z gzikiem @ Pyra Bar'],
      backup: [
        {label:'12:00 鐘樓秀濕滑', where:'牛角麵包博物館內現場互動秀', why:'PLN 25 · 室內可看做麵包，比鐘樓秀深度高'},
        {label:'雨天備案', where:'Stary Browar 商場 + 帝王城堡內部', why:'兩處步行 10 分相連，全程室內可消磨 3 h'},
      ],
    },
    {
      n: 7, date: '10/30 (五)', city: '華沙',
      title: 'POLIN + 起義 + 皇家城堡',
      headline: '華沙告別日 · 三大博物館',
      tag: 'Capital',
      intensity: '高',
      hardConstraints: ['POLIN、起義博物館、皇家城堡皆需控制停留上限', '皇家城堡最後入場前抵達', '晚餐建議預約'],
      mustBook: ['POLIN 波蘭猶太人歷史博物館', '華沙起義博物館', '皇家城堡', '華沙最後晚餐'],
      compressible: ['POLIN 看主展重點', '起義博物館抓核心展區', '皇家城堡控制在 60–90 分鐘'],
      weather: '10° / 4°',
      steps: [
        {t:'10:00', label:'★ POLIN 猶太博物館', sub:'線上預約 · 含中文語音', cost:'PLN 45 (週四免費)', dur:'2.5 h'},
        {t:'13:30', label:'午餐 Tel Aviv Urban', cost:'PLN 50–80', dur:'1 h'},
        {t:'14:30', label:'★ 華沙起義博物館', sub:'3D 影院 · 互動區', cost:'PLN 35 / discount 30', dur:'2 h'},
        {t:'17:00', label:'★ 皇家城堡內部', sub:'最後入場 · 林布蘭', cost:'PLN 60 (週三免費)', dur:'1.5 h'},
        {t:'19:30', label:'老城最後晚餐', sub:'U Fukiera / Polka', cost:'PLN 120–200', dur:'1.5 h'},
        {t:'21:00', label:'老城廣場夜燈漫步', sub:'自由收尾'},
      ],
      eat: ['Żurek 酸黑麥湯 @ U Fukiera', 'Pączki @ A. Blikle 1869'],
      warn: '蕭邦博物館 2026 全年閉館整修，2027/1 才重開',
      extend: [
        {label:'Bulwary Wiślane 維斯瓦河畔', when:'21:00 後老城散步延伸', why:'河濱步道 + 沙灘酒吧，皇家城堡步行 10–15 分，適合晚餐後收尾散步，免費'},
        {label:'Neon Museum 霓虹燈博物館', when:'若提前結束起義博物館可插入', why:'Praga 區，共產時期霓虹招牌收藏，PLN 20，與起義博物館同路線可順走'},
        {label:'Praga 區塗鴉與 Koneser 舊釀酒廠', when:'午餐後彈性時段', why:'起義博物館到皇家城堡之間若時間寬裕，可繞道河對岸 Praga 感受工業改造街區，步行或電車皆可'},
        {label:'科學文化宮 30F 觀景台夜景版', when:'皇家城堡後、晚餐前', why:'PLN 25，傍晚天黑後夜景與白天不同調性，可取代或加碼原本雨天備案'},
      ],
      backup: [
        {label:'三館太累', where:'擇 POLIN + 起義 二選一 → 多留 1.5 h 給城堡', why:'POLIN 動線完整需 3 h，起義內容沉重，連看會疲乏'},
        {label:'天氣轉壞', where:'科學文化宮 30 樓觀景台（室內）', why:'PLN 25 · 45 min · 直通老城地鐵，雨天備案'},
      ],
    },
    {
      n: 8, date: '10/31 (六)', city: '華沙 → 多哈',
      title: '機場日 · 14:40 QR 260 起飛',
      headline: '從容收尾 · SKM 機場線 20 分鐘',
      tag: 'Departure',
      intensity: '低',
      hardConstraints: ['11:00 前抵達華沙蕭邦機場', '如需退稅需預留更多機場時間', '不排正式景點'],
      mustBook: [],
      compressible: ['飯店周邊散步', '最後採買'],
      weather: '9° / 3°',
      steps: [
        {t:'08:00', label:'早餐 + 老城散步', cost:'PLN 40', dur:'1.5 h'},
        {t:'10:30', label:'退房 → Warszawa Centralna', dur:'10 min'},
        {t:'10:40', label:'SKM S2/S3', cost:'PLN 4.4', dur:'20 min'},
        {t:'11:00', label:'抵 Chopin 第一航廈'},
        {t:'11:15', label:'退稅蓋章', sub:'Global Blue / Planet 海關櫃台', dur:'15–30 min'},
        {t:'11:30', label:'報到 + 安檢', dur:'1 h'},
        {t:'14:40', label:'★ QR 260 起飛', sub:'WAW → DOH → HKG → TPE'},
      ],
      backup: [
        {label:'班機提早 2 h', where:'蕭邦機場 1F Costa Coffee · 觀景窗', why:'退稅 + 安檢順可能 12:30 就過關，1F 貴賓區外有平價咖啡'},
        {label:'紀念品最後採買', where:'Wedel + Krówki 機場店', why:'1F 出境前最後一站，伴手禮價差 +10–15% 但方便'},
      ],
    },
  ],
  cities: [
    {key:'WAW', name:'華沙', pl:'Warszawa', tag:'CAPITAL', nights:'1 + 2', totalNights:3, stayNote:'首晚倒時差 + 回程兩晚收尾', vibe:'鋼鐵摩天 × 重建老城', highlights:['POLIN 猶太博物館','起義博物館','皇家城堡','Krakowskie Przedmieście']},
    {key:'KRK', name:'克拉科夫', pl:'Kraków', tag:'OLD WORLD', nights:2, totalNights:2, stayNote:'兩晚承接老城、Auschwitz、鹽礦', vibe:'中世紀石板路 × 千年王城', highlights:['Wawel 城堡','中央市集 Rynek','Auschwitz 一日往返','Kazimierz 猶太區']},
    {key:'WRO', name:'樂斯拉夫', pl:'Wrocław', tag:'700 DWARFS', nights:1, vibe:'700 小矮人 × 煤氣燈點燈', highlights:['百年廳 UNESCO','全景畫 Panorama','座堂島 Ostrów Tumski','糖果屋雙屋']},
    {key:'POZ', name:'波茲南', pl:'Poznań', tag:'CRADLE', nights:1, vibe:'波蘭文明發源 × 山羊報時', highlights:['教堂島 Ostrów Tumski','12:00 山羊鐘樓秀','聖馬丁牛角麵包 PGI','帝王城堡']},
  ],
  trains: [
    {seg:'WAW → KRK', date:'10/25', type:'EIP', dep:'09:00', arr:'11:25', dur:'2h25', price:'130–180'},
    {seg:'KRK ⇄ Auschwitz', date:'10/26', type:'BUS', dep:'07:30', arr:'14:30', dur:'1h30 ×2', price:'30'},
    {seg:'KRK → WRO', date:'10/27', type:'IC', dep:'19:30', arr:'22:20', dur:'2h50', price:'60–110'},
    {seg:'WRO → POZ', date:'10/28', type:'IC', dep:'19:00', arr:'21:20', dur:'2h20', price:'50–90'},
    {seg:'POZ → WAW', date:'10/29', type:'EIP', dep:'17:30', arr:'19:50', dur:'2h20', price:'90–150'},
  ],

  bookingTiers: [
    {tier:'第一優先', note:'一定要先確認', items:[
      {name:'Auschwitz 官方英文導覽', url:'https://visit.auschwitz.org/'},
      {name:'Wieliczka 鹽礦英文團', url:'https://www.wieliczka-saltmine.com/'},
      {name:'華沙 → 克拉科夫火車', url:'https://www.intercity.pl/en/'},
      {name:'克拉科夫 → 樂斯拉夫火車', url:'https://www.intercity.pl/en/'},
      {name:'樂斯拉夫 → 波茲南火車', url:'https://www.intercity.pl/en/'},
      {name:'波茲南 → 華沙火車', url:'https://www.intercity.pl/en/'},
    ]},
    {tier:'第二優先', note:'建議先買或預約', items:[
      {name:'辛德勒工廠', url:'https://mhk.pl/branches/oskar-schindlers-enamel-factory'},
      {name:'POLIN 波蘭猶太人歷史博物館', url:'https://polin.pl/en'},
      {name:'華沙起義博物館', url:'https://www.1944.pl/en'},
      {name:'皇家城堡', url:'https://www.zamek-krolewski.pl/en'},
      {name:'牛角麵包博物館', url:'https://rogalowemuzeum.pl/en/'},
      {name:'拉茨瓦維採全景畫', url:'https://mnwr.pl/en/category/branches/panorama-raclawicka/'},
    ]},
    {tier:'餐廳與備案', note:'旅行品質加分', items:[
      {name:'克拉科夫 Kazimierz 晚餐', url:'https://www.google.com/maps/search/?api=1&query=Kazimierz+Krakow+restaurants'},
      {name:'華沙最後晚餐', url:'https://www.google.com/maps/search/?api=1&query=Warsaw+old+town+Polish+restaurant'},
      {name:'樂斯拉夫午餐或晚餐', url:'https://www.google.com/maps/search/?api=1&query=Wroclaw+old+town+Polish+restaurant'},
      {name:'波茲南老城午餐', url:'https://www.google.com/maps/search/?api=1&query=Poznan+old+town+restaurant'},
    ]},
  ],

  flights: {
    out: [
      {code:'CX 479',  leg:'TPE → HKG', when:'10/23 五 21:05 → 23:05', dur:'2h00m'},
      {code:'⇄ HKG',   leg:'轉機',       when:'2h20m', dur:'', layover:true},
      {code:'QR 815',  leg:'HKG → DOH', when:'10/24 六 01:25 → 04:50', dur:'8h25m'},
      {code:'⇄ DOH',   leg:'轉機',       when:'3h40m', dur:'', layover:true},
      {code:'QR 259',  leg:'DOH → WAW', when:'10/24 六 08:30 → 13:30', dur:'6h00m'},
    ],
    back: [
      {code:'QR 260',  leg:'WAW → DOH', when:'10/31 六 14:40 → 22:10', dur:'6h30m'},
      {code:'⇄ DOH',   leg:'轉機',       when:'3h55m', dur:'', layover:true},
      {code:'QR 818',  leg:'DOH → HKG', when:'11/1 日 02:05 → 14:50', dur:'7h45m'},
      {code:'⇄ HKG',   leg:'轉機',       when:'4h50m', dur:'', layover:true},
      {code:'BR 872',  leg:'HKG → TPE', when:'11/1 日 19:40 → 21:25', dur:'1h45m'},
    ],
  },

  stay: [
    {city:'華沙', en:'Warszawa', pick:'Śródmieście Północne / Powiśle', note:'Śródmieście 交通最便利、地鐵 1/2 線交會；老城氣氛佳但晚上冷清；Praga 河東岸藝術替代區。', tip:'兼顧便利與在地感'},
    {city:'克拉科夫', en:'Kraków', pick:'Kazimierz 或 Stradom', note:'老城 5 分鐘步行可達景點但週末喧鬧；Kazimierz 餐酒密集文青氛圍；Podgórze 安靜在地。', tip:'想睡好覺住 Kazimierz；想熱鬧住老城正中'},
    {city:'樂斯拉夫', en:'Wrocław', pick:'Stare Miasto', note:'城本來就不大，住老城最合理。', tip:'老城是首選，無須考慮其他區'},
    {city:'波茲南', en:'Poznań', pick:'Stary Rynek 周邊', note:'廣場周邊步行可達山羊鐘樓秀、教堂島；Stary Browar 商圈消費低。', tip:'四城物價最低'},
  ],

  tickets: [
    {city:'華沙', items:[
      ['皇家城堡', 'PLN 60 · 週三免費'],
      ['POLIN 猶太歷史', 'PLN 45 · 週四免費'],
      ['華沙起義博物館', 'PLN 35 · discount 30'],
      ['蕭邦博物館', '2026 整年閉館'],
      ['科學文化宮觀景台', 'PLN 25'],
      ['MSN 現代藝術博物館', 'Gallery A 免費 · 18:00 後晚間票 PLN 30'],
    ]},
    {city:'克拉科夫', items:[
      ['瓦維爾城堡套票', 'PLN 45–65'],
      ['辛德勒工廠', 'PLN 38'],
      ['聖瑪麗教堂登塔', 'PLN 20'],
      ['奧斯威辛 Educator 導覽', 'PLN 150'],
      ['維利奇卡鹽礦', 'from PLN 131'],
      ['地下市集博物館', 'PLN 32'],
    ]},
    {city:'樂斯拉夫', items:[
      ['百年廳 Hala Stulecia', 'PLN 30'],
      ['拉茨瓦維採全景畫', 'PLN 50'],
    ]},
    {city:'波茲南', items:[
      ['牛角麵包博物館', 'PLN 25'],
      ['帝王城堡', 'PLN 16'],
      ['古市政廳博物館', 'PLN 10'],
    ]},
  ],

  foods: [
    {n:'01', cn:'波蘭餃子', pl:'Pierogi', desc:'國民料理，半月形餃子有鹹甜兩款。最經典 Pierogi Ruskie（馬鈴薯加 twaróg 起司）。'},
    {n:'02', cn:'獵人燉菜', pl:'Bigos', desc:'波蘭國菜。酸菜 + 新鮮高麗菜 + 多種肉長時間慢燉，每位媽媽都有自家配方。'},
    {n:'03', cn:'酸黑麥湯', pl:'Żurek', desc:'發酵黑麥麵粉熬製，配香腸水煮蛋盛在挖空麵包碗，湯喝完碗也吃掉。'},
    {n:'04', cn:'炸豬排', pl:'Kotlet Schabowy', desc:'波蘭家庭週日必備。豬里肌錘薄裹麵包粉炸金黃，配馬鈴薯泥酸菜。'},
    {n:'05', cn:'包心菜捲', pl:'Gołąbki', desc:'意為「小鴿子」。高麗菜葉包米飯絞肉，淋番茄醬汁烘烤。'},
    {n:'06', cn:'波蘭披薩', pl:'Zapiekanka', desc:'長棍麵包剖半鋪蘑菇起司火腿烤製。1970 年代誕生，Plac Nowy 圓亭最有名。'},
    {n:'07', cn:'波蘭甜甜圈', pl:'Pączki', desc:'油炸酵母麵團，玫瑰果醬內餡。Blikle / Stara Pączkarnia 公認最佳。'},
    {n:'08', cn:'起司蛋糕 / 蘋果派', pl:'Sernik / Szarlotka', desc:'Sernik twaróg 起司蛋糕比紐約款輕盈濕潤；Szarlotka 蘋果派配香草冰淇淋。'},
    {n:'09', cn:'圓圈麵包 PGI', pl:'Obwarzanek', desc:'克拉科夫街頭環形麵包，類似貝果但更輕。歐盟地理標誌保護，PLN 3–5。'},
    {n:'10', cn:'煙燻羊乳酪', pl:'Oscypek', desc:'塔特拉山牧羊人手工製作，鹽水浸泡後針葉樹煙燻。可炙烤淋蔓越莓醬。'},
    {n:'11', cn:'馬鈴薯餅', pl:'Placki Ziemniaczane', desc:'馬鈴薯刨絲混蛋液煎成酥脆，配酸奶油或匈牙利風味牛肉燉醬。'},
    {n:'12', cn:'野牛草伏特加', pl:'Żubrówka', desc:'比亞沃韋札森林野牛草浸泡，每瓶都有真草。經典喝法 Tatanka：配蘋果汁。'},
  ],

  cityFood: [
    {city:'華沙', en:'Warszawa', items:[
      {tag:'美食市集', name:'Hala Koszyki', note:'百年美食市集', book:'walk'},
      {tag:'Pierogi', name:'Zapiecek', note:'老城多家分店', book:'walk'},
      {tag:'熱巧克力', name:'E. Wedel Pijalnia', note:'蕭邦曾常去', book:'queue'},
      {tag:'米其林必比登', name:'U Fukiera / Polka', note:'Żurek 麵包碗', book:'must'},
      {tag:'牛奶吧', name:'Bar Prasowy', note:'套餐 PLN 25–35', book:'walk'},
      {tag:'Pączki', name:'A. Blikle', note:'1869 年老字號', book:'queue'},
      {tag:'河畔酒吧', name:'Plaża Poniatówka', note:'維斯瓦河畔沙灘酒吧，日落後氣氛佳', book:'walk', map:'https://www.google.com/maps/search/?api=1&query=Plaza+Poniatowka+Warszawa'},
      {tag:'猶太料理', name:'Beit Warszawa 周邊小館', note:'POLIN 附近，可接續博物館主題', book:'walk', map:'https://www.google.com/maps/search/?api=1&query=POLIN+Museum+restaurants+Warszawa'},
      {tag:'精釀啤酒', name:'Warszawski Klub Piwoszy', note:'老城周邊，適合最後一晚小酌', book:'walk'},
      {tag:'伴手甜點', name:'Cukiernia Pawełek', note:'手工巧克力與糖果，適合最後採買', book:'walk'},
      {tag:'年度開幕獎 2026', name:'WANDAL', note:'必比登 · 顛覆式波蘭菜，Day 7 晚餐候選', book:'must', map:'https://www.google.com/maps/search/?api=1&query=WANDAL+restauracja+Warszawa'},
    ]},
    {city:'克拉科夫', en:'Kraków', items:[
      {tag:'米其林必比登', name:'Starka / Szara Gęś', note:'Kazimierz 與廣場', book:'must'},
      {tag:'地窖晚餐', name:'Pod Aniołami', note:'燭光氛圍', book:'must'},
      {tag:'文青早午餐', name:'Charlotte', note:'Plac Szczepański', book:'queue'},
      {tag:'猶太料理', name:'Hamsa / Klezmer-Hois', note:'Kazimierz', book:'walk'},
      {tag:'Pierogi', name:'Pierogarnia Krakowiacy', note:'老城手工餃子', book:'walk'},
      {tag:'Zapiekanka', name:'Plac Nowy 圓亭', note:'Endzior / Krzysiek', book:'queue', map:'https://www.google.com/maps/search/?api=1&query=Plac+Nowy+Okraglak+Krakow'},
      {tag:'米其林二星', name:'Bottiglieria 1881', note:'2026 連續第四年二星 · 全波蘭唯一 · 需提前 2 週+ 訂位', book:'must', map:'https://www.google.com/maps/search/?api=1&query=Bottiglieria+1881+Krakow'},
      {tag:'Sernik', name:'Cukiernia Michałek', note:'百年甜點老店', book:'walk'},
      {tag:'必比登 2026', name:'Bufet KRK', note:'Bottiglieria 1881 平價副牌，免長預約', book:'queue', map:'https://www.google.com/maps/search/?api=1&query=Bufet+KRK+Krakow'},
      {tag:'必比登 2026', name:'Nat Bistro', note:'年度青年主廚獎 Ida Malec · 自然酒', book:'must', map:'https://www.google.com/maps/search/?api=1&query=Nat+Bistro+Krakow'},
    ]},
    {city:'樂斯拉夫', en:'Wrocław', items:[
      {tag:'西里西亞', name:'Konspira', note:'80 年代反共主題', book:'walk'},
      {tag:'Pierogi', name:'Pierogarnia Stary Młyn', note:'廣場旁', book:'walk', map:'https://www.google.com/maps/search/?api=1&query=Pierogarnia+Stary+Mlyn+Wroclaw'},
      {tag:'融合料理', name:'Karczma Lwowska', note:'波蘭/烏克蘭', book:'walk'},
      {tag:'市場午餐', name:'Hala Targowa', note:'PLN 20–30', book:'walk'},
      {tag:'精釀啤酒', name:'Browar Stu Mostów', note:'旗艦廠', book:'walk'},
      {tag:'米其林必比登', name:'Pod Fredrą / Jadka', note:'廣場旁傳統', book:'must'},
      {tag:'米其林一星 2026', name:'BABA', note:'新升星 · 波蘭菜當代詮釋，午間較易訂', book:'must', map:'https://www.google.com/maps/search/?api=1&query=BABA+restauracja+Wroclaw'},
      {tag:'必比登 2026', name:'Pijalni', note:'重風味輕形式', book:'walk', map:'https://www.google.com/maps/search/?api=1&query=Pijalni+Wroclaw'},
    ]},
    {city:'波茲南', en:'Poznań', items:[
      {tag:'Lech 啤酒', name:'Stary Browar', note:'古釀酒廠改造', book:'walk'},
      {tag:'燒烤', name:'Whiskey In The Jar', note:'燒烤名店', book:'must'},
      {tag:'PGI 牛角', name:'Cukiernia Kandulski', note:'百年老店', book:'queue'},
      {tag:'家常', name:'Pyra Bar', note:'馬鈴薯佐凝乳', book:'walk'},
      {tag:'歷史名宅', name:'Hotel Bazar', note:'蕭邦曾下榻', book:'walk'},
      {tag:'重口味', name:'Stary Maglownik', note:'鴨血酸湯', book:'walk'},
    ]},
  ],

  foodBackup: [
    {city:'華沙', en:'Warszawa', items:[
      {tag:'必比登備案', name:'Kieliszki na Próżnej', note:'酒杯牆名店 · 波蘭菜配酒，WANDAL 訂不到的首替', book:'must', map:'https://www.google.com/maps/search/?api=1&query=Kieliszki+na+Proznej+Warszawa'},
      {tag:'必比登備案', name:'kontakt', note:'小館精緻路線，座位少', book:'must', map:'https://www.google.com/maps/search/?api=1&query=kontakt+restauracja+Warszawa'},
      {tag:'必比登備案', name:'Wyraj', note:'斯拉夫傳統食材當代化', book:'must', map:'https://www.google.com/maps/search/?api=1&query=Wyraj+restauracja+Warszawa'},
      {tag:'傳統備案', name:'Stary Dom', note:'老派滿漢波蘭菜 · 韃靼牛肉名店，離市中心稍遠', book:'must', map:'https://www.google.com/maps/search/?api=1&query=Restauracja+Stary+Dom+Warszawa'},
      {tag:'傳統備案', name:'Podwale 25', note:'啤酒館巨無霸豬腳 · 老城旁 · 氣氛熱鬧', book:'queue', map:'https://www.google.com/maps/search/?api=1&query=Podwale+25+Kompania+Piwna+Warszawa'},
      {tag:'牛奶吧備案', name:'Bar Mleczny Familijny', note:'Nowy Świat 上 · Bar Prasowy 排隊時的替代', book:'walk', map:'https://www.google.com/maps/search/?api=1&query=Bar+Mleczny+Familijny+Nowy+Swiat+Warszawa'},
      {tag:'Praga 區', name:'Pyzy Flaki Gorące', note:'玻璃罐裝 pyzy 馬鈴薯糰 · Day 7 Praga 行程順路', book:'queue', map:'https://www.google.com/maps/search/?api=1&query=Pyzy+Flaki+Gorace+Warszawa'},
      {tag:'甜點備案', name:'Lukullus', note:'新派法波混血甜點房，多分店', book:'walk', map:'https://www.google.com/maps/search/?api=1&query=Cukiernia+Lukullus+Warszawa'},
      {tag:'快食備案', name:'Manekin', note:'波蘭可麗餅 naleśniki 專門店 · 平價大份', book:'queue', map:'https://www.google.com/maps/search/?api=1&query=Manekin+Warszawa'},
    ]},
    {city:'克拉科夫', en:'Kraków', items:[
      {tag:'必比登備案', name:'NOAH', note:'Kazimierz 以色列菜 · Hamsa 滿座時的替代', book:'must', map:'https://www.google.com/maps/search/?api=1&query=NOAH+restaurant+Krakow'},
      {tag:'必比登備案', name:'MOLÁM', note:'泰菜 · 連日波蘭菜吃膩時的出口', book:'must', map:'https://www.google.com/maps/search/?api=1&query=MOLAM+Krakow'},
      {tag:'必比登備案', name:'Folga', note:'波蘭菜輕盈版 · 價格友善', book:'must', map:'https://www.google.com/maps/search/?api=1&query=Folga+restauracja+Krakow'},
      {tag:'傳統備案', name:'Morskie Oko', note:'塔特拉山區高地菜 · 烤 oscypek 與烤肉 · 現場民俗樂', book:'must', map:'https://www.google.com/maps/search/?api=1&query=Morskie+Oko+restauracja+Krakow'},
      {tag:'傳統備案', name:'Miód Malina', note:'「蜂蜜覆盆子」· 廣場旁氣氛店，觀光但穩定', book:'must', map:'https://www.google.com/maps/search/?api=1&query=Miod+Malina+Krakow'},
      {tag:'傳統備案', name:'Pod Wawelem', note:'城堡腳下啤酒館 · 巨份炸豬排，快食快走', book:'queue', map:'https://www.google.com/maps/search/?api=1&query=Pod+Wawelem+Kompania+Kuflowa+Krakow'},
      {tag:'家常備案', name:'Kuchnia u Doroty', note:'Kazimierz 在地家常 · 波蘭媽媽味 · 平價', book:'walk', map:'https://www.google.com/maps/search/?api=1&query=Kuchnia+u+Doroty+Krakow'},
      {tag:'Pierogi 備案', name:'Przystanek Pierogarnia', note:'現包現煮小店 · Pierogarnia Krakowiacy 排隊時替代', book:'walk', map:'https://www.google.com/maps/search/?api=1&query=Przystanek+Pierogarnia+Krakow'},
      {tag:'咖啡甜點', name:'Cafe Camelot', note:'老城巷內百年氛圍 · szarlotka 蘋果派', book:'queue', map:'https://www.google.com/maps/search/?api=1&query=Cafe+Camelot+Krakow'},
      {tag:'冰淇淋', name:'Good Lood', note:'克拉科夫現象級冰淇淋 · 每日限定口味', book:'queue', map:'https://www.google.com/maps/search/?api=1&query=Good+Lood+Krakow'},
    ]},
    {city:'樂斯拉夫', en:'Wrocław', items:[
      {tag:'米其林一星 2026', name:'Most', note:'BABA 之外的另一顆新星 · 兩者擇一卡位即可', book:'must', map:'https://www.google.com/maps/search/?api=1&query=Most+restauracja+Wroclaw'},
      {tag:'必比登備案', name:'IDA kuchnia i wino', note:'區域波蘭菜配酒 · 老城 Łazienna 街', book:'must', map:'https://www.google.com/maps/search/?api=1&query=IDA+kuchnia+i+wino+Wroclaw'},
      {tag:'必比登備案', name:'Tarasowa', note:'河景露台 · 天氣好時首選', book:'must', map:'https://www.google.com/maps/search/?api=1&query=Tarasowa+restauracja+Wroclaw'},
      {tag:'傳統備案', name:'Kurna Chata', note:'民俗風家常波蘭菜 · 廣場旁 · 平價大份', book:'queue', map:'https://www.google.com/maps/search/?api=1&query=Kurna+Chata+Wroclaw'},
      {tag:'廣場備案', name:'Bernard', note:'捷克餐酒館 · 廣場直視座位 · 營業時間長', book:'walk', map:'https://www.google.com/maps/search/?api=1&query=Bernard+restauracja+Rynek+Wroclaw'},
      {tag:'快食備案', name:'Pierogarnia Stary Młyn（二店）', note:'主店客滿時問二店或外帶', book:'walk', map:'https://www.google.com/maps/search/?api=1&query=Pierogarnia+Stary+Mlyn+Wroclaw'},
    ]},
    {city:'波茲南', en:'Poznań', items:[
      {tag:'米其林一星', name:'Muga', note:'波茲南唯一星級 · 想升級 Day 6 午餐的天花板選項', book:'must', map:'https://www.google.com/maps/search/?api=1&query=Muga+restauracja+Poznan'},
      {tag:'必比登備案', name:'SPOT.', note:'咖啡烘焙起家的現代小館', book:'must', map:'https://www.google.com/maps/search/?api=1&query=SPOT+restauracja+Poznan'},
      {tag:'必比登備案', name:'Fromażeria', note:'起司主題 · 酒配起司輕食', book:'must', map:'https://www.google.com/maps/search/?api=1&query=Fromazeria+Poznan'},
      {tag:'必比登備案', name:'Posto', note:'義大利菜 · 波蘭菜吃膩時的出口', book:'must', map:'https://www.google.com/maps/search/?api=1&query=Posto+restauracja+Poznan'},
      {tag:'傳統備案', name:'Ratuszova', note:'市政廳正對面地窖餐廳 · 看完山羊直接下樓', book:'queue', map:'https://www.google.com/maps/search/?api=1&query=Ratuszova+Poznan'},
      {tag:'傳統備案', name:'Brovaria', note:'Stary Rynek 上的自釀啤酒餐廳 · 順路一杯', book:'walk', map:'https://www.google.com/maps/search/?api=1&query=Brovaria+Poznan'},
      {tag:'早餐備案', name:'Modra Kuchnia', note:'在地人氣早午餐 · 出發回華沙前的悠閒早餐', book:'queue', map:'https://www.google.com/maps/search/?api=1&query=Modra+Kuchnia+Poznan'},
    ]},
  ],

  safety: {
    emergency: [
      ['歐洲通用緊急', '112'],
      ['警察 Policja', '997'],
      ['消防 Straż Pożarna', '998'],
      ['救護 Pogotowie', '999'],
      ['市政警察', '986'],
    ],
    embassy: [
      ['駐波蘭台北代表處', 'Al. Jerozolimskie 179, Warszawa'],
      ['辦公室電話', '+48 22 213 0060'],
      ['急難救助專線', '+48 668 027 574'],
      ['外交部 24h 專線', '+886 800 085 095'],
    ],
    tips: [
      {label:'觀光陷阱', text:'廣場「免費試衣」拍照後索費；中央車站黑計程車（堅持 Bolt / Uber）；市中心換匯陷阱（Kantor 買賣價差 ≤ 1.5%）'},
      {label:'禮儀', text:'進教堂脫帽；Auschwitz 禁笑鬧自拍；勿把波蘭當俄國；餐廳小費約 10%'},
      {label:'治安', text:'全球安全指數前 30。注意觀光區扒手（火車站、Rynek）；貴重物品用前背包'},
      {label:'就醫', text:'自來水可生飲；Apteka 藥局普及；建議投保涵蓋緊急醫療的旅平險'},
    ],
  },

  practical: [
    {tag:'左行寄物', name:'火車站 Locker', note:'WAW Centralna / KRK Główny / WRO Główny / POZ Główny 都有自助 locker。小箱 PLN 8–12 / 大箱 PLN 12–18 · 24 h 為一單位。'},
    {tag:'換錢', name:'Kantor 民間匯兌', note:'機場 / 觀光區匯率最差。市區「Internet Kantor」、「Kantor Pomocna」買賣價差 ≤ 1.5%。⚠ 看到「0% Commission」要警覺。'},
    {tag:'SIM 卡', name:'Play / Plus / Orange', note:'蕭邦機場到達層櫃台、市區 Empik / Żabka 都有。PLN 30 起含 30 天無限上網 + 通話。台灣免簽歐盟漫遊不適用波蘭費率。'},
    {tag:'付款', name:'信用卡 + Revolut', note:'四城 95% 商家收 Visa / Master，含廣場攤販。Apple Pay 普及。建議帶 PLN 200–300 現金應付小費 / 教堂 / 鄉間。'},
    {tag:'退稅', name:'Tax Free 海關蓋章', note:'單筆 PLN 200 以上於 Tax Free 標誌商店可退 8–18% VAT。離境前在蕭邦機場 / KRK 機場海關櫃台蓋章再投退稅信箱。'},
    {tag:'交通卡', name:'單程票 vs 24h 票', note:'華沙 / 克拉科夫 24 h 票約 PLN 18，當日搭 3 趟以上划算。Jakdojade / Koleo App 查時刻 + 直接買票。'},
  ],
  reservations: [
    {when:'出發前 60+ 天', what:'機票確認 + 各城住宿（此階段火車票尚未開賣，不用急）'},
    {when:'出發前 30 天（約 9/25 起，逐班開賣）', what:'PKP Intercity Super Promo 於各班發車前 30 天開賣（首班 10/25 WAW→KRK 約 9/25 起），鎖定四段火車車票（含 Day4 KRK→WRO 19:30 班次，intercity.pl）；開賣當週密集比價，越早訂越便宜'},
    {when:'出發前 21 天', what:'Auschwitz 英文官方導覽（visit.auschwitz.org · 旺季 14 天前售完）'},
    {when:'出發前 14–21 天', what:'Wieliczka 鹽礦英文 Tourist Route 10:00 場（官方標示 2–3 h、from PLN 131；英文場名額少需早卡位）'},
    {when:'出發前 14 天', what:'POLIN 猶太博物館 + 華沙起義博物館 + 辛德勒工廠 10/25 (日) 17:30 最後入場場次（mhk.pl/en）'},
    {when:'出發前 3–4 週', what:'米其林餐廳：Bottiglieria 1881（二星，最搶）、BABA / Most（樂斯拉夫新星，僅停留一晚零彈性）、WANDAL、Pod Aniołami（TheFork / OpenTable / 餐廳官網）'},
    {when:'抵達當日', what:'隔日 Wawel 國家廳室現場票（限額制，售完只能改廷院）'},
  ],

  shopping: [
    {tag:'陶瓷', name:'Bolesławiec', note:'藍底白點手繪餐具，全球收藏家追捧'},
    {tag:'琥珀', name:'波羅的海琥珀', note:'克拉科夫紡織會館或華沙老城；辨真偽：泡鹽水會浮、靜電可吸紙屑'},
    {tag:'伏特加', name:'Żubrówka / Soplica', note:'野牛草 / 果味，伴手首選'},
    {tag:'巧克力', name:'E. Wedel', note:'1851 年華沙百年品牌'},
    {tag:'糖果', name:'Krówki', note:'波蘭奶油糖，超市到處有'},
    {tag:'剪紙', name:'Wycinanki', note:'庫亞瓦、洛維奇地區傳統'},
    {tag:'起司', name:'Oscypek', note:'塔特拉山區代表性乳酪，可帶上飛機'},
  ],

  cityStories: [
    {
      city:'華沙', en:'Warszawa',
      geo:'維斯瓦河（Wisła）中游西岸，波蘭地理與交通的十字路口。左岸（西）是重建的老城與現代市中心，右岸 Praga 區因 1944 年已被蘇軍佔領而躲過摧毀，保留了戰前原始街景——今日的藝術替代區。',
      history:'二戰中被系統性夷平的城市：1944 華沙起義失敗後，希特勒下令逐街爆破，市區約 85% 化為瓦礫。戰後波蘭人依 18 世紀宮廷畫家 Bellotto（Canaletto）的城市風景畫逐磚重建老城，1980 年以「非典型完整重建案例」列入 UNESCO——你走的老城廣場每一面牆都不到 80 歲，卻承載 700 年的記憶。',
      stories:[
        {title:'美人魚與雙城傳說', text:'華沙市徽是持劍舉盾的美人魚 Syrenka。傳說她與哥本哈根小美人魚是姊妹，一路游進維斯瓦河，被漁民所救後誓言守護此城——所以華沙美人魚是戰鬥形態，哥本哈根那隻是憂鬱形態。'},
        {title:'蕭邦的心臟', text:'蕭邦客死巴黎，遺體葬於拉雪茲神父公墓，但遵其遺願，姊姊將他的心臟帶回華沙，封存在聖十字教堂（Krakowskie Przedmieście 上，Day 1 傍晚散步會經過）的柱子裡。二戰期間曾被納粹取走，戰後歸位。'},
        {title:'一份不受歡迎的禮物', text:'科學文化宮是 1955 年史達林「贈送」的蘇聯式摩天樓，華沙人曾說最棒的觀景點就是它的 30 樓——因為那是全城唯一看不到它的地方。如今旁邊蓋起純白的 MSN 現代美術館（2024 開幕、NYT 2026 必訪 No.2），新舊對峙本身就是展品。'},
        {title:'居禮夫人是華沙人', text:'瑪麗亞·斯克沃多夫斯卡（Maria Skłodowska-Curie）1867 年生於新城區 Freta 街 16 號，是史上唯一在兩個不同科學領域拿諾貝爾獎的人。老城散步腳程內就有她的出生地博物館。'},
      ],
      onSite:[
        '老城廣場地面找「重建前 vs 重建後」對照銅牌',
        '聖十字教堂左側第二根柱：蕭邦心臟安放處',
        'Praga 區（Day 7 已排）注意牆上戰前彈孔與原始磚面——左岸看不到的真跡',
      ],
    },
    {
      city:'克拉科夫', en:'Kraków',
      geo:'維斯瓦河上游，Wawel 城堡建在河畔一座石灰岩丘上——控制河運的天然要塞，也是波蘭王權 500 年的地理支點。老城以歐洲最大中世紀廣場 Rynek Główny（200m × 200m）為核心，街廓自 1257 年大蒙古劫掠後重劃至今未變。',
      history:'1038–1596 年的波蘭王都，歷代國王在 Wawel 加冕與安葬。二戰時因作為納粹總督府所在地而未被戰火摧毀，是波蘭極少數「原裝」的古城——你在克拉科夫摸到的石頭大多是真的中世紀石頭。Kazimierz 原是 1335 年卡齊米日大帝敕建的獨立城市，數百年來是歐洲猶太文化重鎮，戰前 6.5 萬猶太居民戰後僅存數千。',
      stories:[
        {title:'瓦維爾龍', text:'傳說 Wawel 山丘下的洞穴住著噴火龍，吃遍牲口少女。屠龍的不是騎士，而是鞋匠學徒 Skuba——他把硫磺塞進羊皮縫成假羊，龍吞下後渴到狂飲維斯瓦河水，最後爆掉。今日城堡下河畔有一座每隔幾分鐘真的噴火的龍雕像。'},
        {title:'斷在半空的號角', text:'聖瑪利亞教堂塔頂每小時整點吹奏 Hejnał 號角，旋律永遠在同一個音戛然而止——紀念 1241 年蒙古來襲時，吹號示警的哨兵喉嚨中箭、樂聲中斷的傳說。這是全世界少數「以未完成為完成」的城市儀式，Day 2 16:00 廣場行程剛好對到整點。'},
        {title:'廣場底下還有一個廣場', text:'Rynek 地面下 4 公尺是 13 世紀的街面。2005–2010 年考古挖掘後原地做成 Rynek Underground 博物館（Day 2 雨備）——你腳下踩的其實是中世紀商路的天花板。'},
        {title:'兩顆星的城市', text:'2026 米其林把全波蘭唯一二星留給了這裡的 Bottiglieria 1881（連四年），發布典禮也選在克拉科夫 ICE 會議中心舉行——波蘭美食之都的地位官方蓋章。'},
      ],
      onSite:[
        '整點在廣場任一角落停下來等 Hejnał，注意最後一個音的戛然而止',
        '紡織會館二樓迴廊看廣場全景（免費），一樓攤位留到 10/27 採買',
        'Kazimierz Szeroka 街：《辛德勒的名單》多場戲的實景地',
      ],
    },
    {
      city:'樂斯拉夫', en:'Wrocław',
      geo:'奧得河（Odra）在此裂成多條支流，把城市切成 12 座島、以 100 多座橋相連——「波蘭威尼斯」。最老的核心 Ostrów Tumski（座堂島）是千年前的起點，至今保留全歐少數仍由點燈人每晚手工點燃的瓦斯街燈。',
      history:'這座城市 1945 年前叫 Breslau，是德國第六大城。戰後國界西移，德裔居民被遷出，取而代之的是被蘇聯劃走的東部城市利沃夫（Lwów）的波蘭移民——整座城市的人口被「換血」。拉茨瓦維採全景畫正是從利沃夫一起搬來的鎮城之寶，Karczma Lwowska 餐廳的名字也是這段記憶。',
      stories:[
        {title:'小矮人是反抗軍', text:'城裡 600+ 尊銅製小矮人（krasnale）不是行銷噱頭：1980 年代反共團體「橙色替代」（Pomarańczowa Alternatywa）以塗鴉小矮人與荒誕街頭劇嘲諷政權——警察逮捕一個扮小矮人的人有多可笑，體制就有多可笑。2005 年起城市以銅像致敬這段歷史，每一尊都有名字與職業。'},
        {title:'每晚的點燈儀式', text:'日落時分，披斗篷、持長桿的點燈人會逐一點亮 Ostrów Tumski 的 90 餘盞瓦斯燈——歐洲僅存的日常點燈儀式之一。10/28 日落約 16:20，Day 5 傍晚轉場前剛好能看（data.js 已排入點燈）。'},
        {title:'混凝土的世界遺產', text:'百年廳（Hala Stulecia，1913）落成時擁有世界最大跨距的鋼筋混凝土圓頂，直接影響了現代主義建築的走向，2006 年列入 UNESCO——在古蹟之城看一座「未來古蹟」。'},
      ],
      onSite:[
        '廣場周邊開始數小矮人：郵差、消防員、睡在門邊的、推保險箱的——App「Krasnale Wrocław」有地圖',
        '座堂島橋上的情人鎖與瓦斯燈：日落前 15 分鐘卡位',
        '注意市政廳南面的天文鐘與哥德山牆——二戰倖存的原件',
      ],
    },
    {
      city:'波茲南', en:'Poznań',
      geo:'瓦爾塔河（Warta）畔，位居柏林—華沙軸線正中，千年來吃盡東西貿易紅利，至今仍是波蘭的會展之都。城市原點在河中沙洲 Ostrów Tumski（與樂斯拉夫的座堂島同名不同地）。',
      history:'波蘭國家的搖籃：966 年梅什科一世（Mieszko I）在此受洗，波蘭以此為建國元年；最早的君主就葬在波茲南座堂。近代史上同樣硬氣——1956 年 6 月的工人起義是共產波蘭第一場大規模反抗，比華沙、格但斯克都早。',
      stories:[
        {title:'兩隻山羊的贖罪', text:'1551 年市政廳新鐘落成宴上，學徒烤焦了鹿肉，情急偷了兩隻山羊代替；山羊逃上鐘塔，在全城面前頂起角來，逗笑了市長與賓客，因而獲赦。從此市政廳每天 12:00 由機械山羊互撞 12 下——Day 6 正午行程就是為它排的。'},
        {title:'有身分證的麵包', text:'聖馬丁牛角麵包（rogal świętomarciński）受歐盟 PGI 保護：白罌粟籽餡、81 層酥皮、只有波茲南地區持證烘焙坊能做。傳統上 11/11 聖馬丁節當天全城吃掉數百噸——你早到兩週，平日仍買得到，認明店內 PGI 證書（Kandulski 是百年老字號）。'},
        {title:'蕭邦睡過的飯店', text:'Stary Rynek 旁的 Hotel Bazar（1841）是波蘭民族運動的據點，蕭邦 1843 年在此下榻並演奏；1918 年鋼琴家帕德瑞夫斯基在此陽台演說，點燃了大波蘭起義。'},
      ],
      onSite:[
        '11:45 前到 Stary Rynek 卡位看山羊（只演一次，錯過等明天）',
        '市政廳文藝復興立面：波蘭最美的市政廳之一，1550s 義大利建築師 di Quadro 之作',
        '牛角麵包博物館的示範秀會請觀眾上台擀麵——坐前排',
      ],
    },
  ],

  phrases: [
    ['你好（非正式）', 'Cześć', 'chesh-ch'],
    ['您好', 'Dzień dobry', 'jen dob-ri'],
    ['晚安', 'Dobranoc', 'do-bra-nots'],
    ['謝謝', 'Dziękuję', 'jen-koo-yeh'],
    ['請 / 不客氣', 'Proszę', 'pro-sheh'],
    ['是 / 否', 'Tak / Nie', ''],
    ['對不起', 'Przepraszam', 'psheh-pra-sham'],
    ['廁所在哪', 'Gdzie jest toaleta?', ''],
    ['買單', 'Rachunek proszę', ''],
    ['多少錢', 'Ile to kosztuje?', ''],
    ['乾杯', 'Na zdrowie!', 'naz-dro-vyeh'],
    ['真好吃', 'Smaczne!', 'smach-neh'],
  ],

  about: [
    ['語言', '波蘭語（觀光區英語通）'],
    ['電壓', '230V · C/E/F 型插座'],
    ['時區', 'CET（夏令 CEST）'],
    ['台幣換算', '1 PLN ≈ 8 TWD'],
    ['物價水位', '西歐之 50–60%'],
    ['小費文化', '餐廳 10%（非強制）'],
    ['台灣簽證', '免申根簽 90 天'],
    ['ETIAS', '2026 Q4 上線但確切日期未公布，強制生效約至 2027/4 才開始，本次行程機率不受影響 · 費用 EUR 20 · 出發前 1–2 個月上 travel-europe.europa.eu/etias 確認一次即可'],
  ],
};
