// Shared trip data — surfaces the same content across all 3 design directions
window.TRIP = {
  meta: {
    code: 'POLSKA',
    edition: 'Vol. I · No. 1 · 2025–2026',
    dateRange: '2026 / 10 / 24 — 10 / 31',
    nights: 7, days: 8,
    cities: ['Warszawa', 'Kraków', 'Wrocław', 'Poznań'],
    flights: '國泰 + 卡達 + 長榮聯運',
  },
  days: [
    {
      n: 1, date: '10/24 (六)', city: '華沙',
      title: '抵達華沙 · 老城傍晚漫步',
      headline: '13:30 抵蕭邦機場，SKM 進城，老城散步、倒時差',
      tag: 'Arrival',
      weather: '11° / 6°',
      steps: [
        {t:'13:30', label:'抵蕭邦機場', sub:'申根入境 + 提行李 ~75min', cost:'—', dur:'75 min'},
        {t:'14:45', label:'SKM S2/S3', sub:'4.4 PLN · 20 min 進城', cost:'PLN 4.4', dur:'20 min'},
        {t:'15:15', label:'旅館 Check-in', dur:'30 min'},
        {t:'16:45', label:'★ 老城廣場', sub:'皇家城堡 · 美人魚雕像', cost:'免費', dur:'1 h'},
        {t:'18:00', label:'Krakowskie Przedmieście', sub:'黃昏氛圍', cost:'免費', dur:'1 h'},
        {t:'19:00', label:'Pierogi 晚餐', sub:'Zapiecek · Podwale 19', cost:'PLN 35–55'},
        {t:'21:00', label:'早睡倒時差'},
      ],
      eat: ['Pierogi @ Zapiecek', 'Wedel 熱巧克力 @ E. Wedel Pijalnia'],
      backup: [
        {label:'下雨備案', where:'科學文化宮 30F 觀景台', why:'PLN 25 · 室內 + 360° 城景，老城廣場走路 12 分'},
        {label:'時差太累', where:'Łazienki 公園溫室', why:'室內展館 + 蕭邦像，免費，傍晚前可走'},
      ],
      practical: [
        {tag:'寄物', name:'Warszawa Centralna', note:'地下層自助 locker · PLN 8/12 大小箱'},
        {tag:'換錢', name:'Internet Kantor (Marszałkowska)', note:'四城最佳匯率，價差 ≤ 1%'},
        {tag:'SIM', name:'Play / Plus / Orange', note:'機場到達層櫃台，PLN 30 起 30 天無限'},
      ],
    },
    {
      n: 2, date: '10/25 (日)', city: '華沙 → 克拉科夫',
      title: '南下克拉科夫 · 老城三大景點',
      headline: 'EIP Pendolino 09:00 → 11:25 · 頭等艙含早餐',
      tag: 'Transit',
      weather: '12° / 5°',
      train: {type:'EIP', from:'WAW', to:'KRK', dep:'09:00', arr:'11:25', dur:'2h25', price:'PLN 130–180'},
      steps: [
        {t:'09:00', label:'EIP Pendolino 出發', sub:'頭等艙 · Wi-Fi · 早餐', cost:'PLN 130–180', dur:'2h25'},
        {t:'11:25', label:'抵 Kraków Główny', dur:'10 min 拖行李'},
        {t:'13:00', label:'★ 瓦維爾大教堂', sub:'週日 12:30–17:00', cost:'PLN 26', dur:'45 min'},
        {t:'14:00', label:'★ Wawel 國家廳室', sub:'最後入場 15:10 ⚠', cost:'PLN 45–65', dur:'1.5 h'},
        {t:'16:00', label:'★ 中央廣場 + 聖瑪利亞', sub:'整點 Hejnał 號角', cost:'PLN 20 (登塔)', dur:'1 h'},
        {t:'17:00', label:'紡織會館 Sukiennice', cost:'免費入場', dur:'30 min'},
        {t:'19:00', label:'晚餐 Pod Aniołami / Miód Malina', cost:'PLN 80–140'},
      ],
      eat: ['Obwarzanek 圓圈麵包 (PGI)', 'Pierogi @ Pierogarnia Krakowiacy', 'Pod Aniołami 地窖晚餐'],
      backup: [
        {label:'雨天替代', where:'地下市集博物館 Rynek Underground', why:'廣場下方歷史展，PLN 32，1.5h 室內'},
        {label:'廳室客滿', where:'Czartoryski 博物館（達文西《抱貂的女子》）', why:'PLN 35，藏世界級畫作，老城內 5 分'},
      ],
      practical: [
        {tag:'寄物', name:'Kraków Główny 主月台', note:'自助 locker PLN 9/15，火車站直達廣場 8 分'},
        {tag:'換錢', name:'Kantor Pomocna (廣場 14 號)', note:'廣場周邊最佳，比 Kantor.pl 便宜 0.5%'},
      ],
    },
    {
      n: 3, date: '10/26 (一)', city: '克拉科夫',
      title: 'Auschwitz-Birkenau · 一日往返',
      headline: '波蘭最沉重也最重要的一天',
      tag: 'Memorial',
      weather: '10° / 4°',
      train: {type:'BUS', from:'KRK', to:'Oświęcim', dep:'07:30', arr:'09:00', dur:'1h30 ×2', price:'PLN 15 ×2'},
      steps: [
        {t:'07:30', label:'Lajkonik 巴士', sub:'MDA D9 / D10 月台', cost:'PLN 15', dur:'1h30'},
        {t:'09:00', label:'抵 Auschwitz I', sub:'安檢、寄包、領耳機', dur:'30 min'},
        {t:'10:00', label:'★ 英文官方導覽', sub:'一館 + 比克瑙 · 3.5h', cost:'PLN 150', dur:'3.5 h'},
        {t:'13:30', label:'導覽結束'},
        {t:'14:30', label:'巴士返克拉科夫', cost:'PLN 15', dur:'1h30'},
        {t:'16:00', label:'抵 Kraków · 休息'},
        {t:'18:00', label:'安靜晚餐沉澱情緒', cost:'PLN 60–100'},
      ],
      warn: '須提前 2–3 週於 visit.auschwitz.org 預約英文官方導覽 · 開團前 30 分鐘抵達完成安檢',
      backup: [
        {label:'戶外為主 · 必備雨具', where:'比克瑙營區戶外 80%', why:'導覽風雨無阻，請穿防水鞋 + 帶折傘'},
        {label:'若無導覽額度', where:'維利奇卡鹽礦', why:'室內 PLN 159，2 h 導覽，可線上預約替代行程'},
      ],
    },
    {
      n: 4, date: '10/27 (二)', city: '克拉科夫 → 弗羅茨瓦夫',
      title: '辛德勒工廠 + Kazimierz · 傍晚轉場',
      headline: 'IC 17:30 → 21:00 · 3h30',
      tag: 'Transit',
      weather: '11° / 5°',
      train: {type:'IC', from:'KRK', to:'WRO', dep:'17:30', arr:'21:00', dur:'3h30', price:'PLN 60–110'},
      steps: [
        {t:'10:00', label:'★ 辛德勒工廠', sub:'mhk.pl/en 線上預約', cost:'PLN 38', dur:'1.5 h'},
        {t:'12:15', label:'★ Plac Nowy zapiekanka', sub:'Endzior / Krzysiek', cost:'PLN 18–25', dur:'30 min'},
        {t:'13:30', label:'Kazimierz 散步', sub:'舊猶太會堂 · Szeroka 街', cost:'免費', dur:'1 h'},
        {t:'15:00', label:'紡織會館採購', dur:'1 h'},
        {t:'17:30', label:'IC 火車出發', cost:'PLN 60–110', dur:'3h30'},
        {t:'21:00', label:'抵 Wrocław Główny'},
      ],
      eat: ['Zapiekanka @ Plac Nowy 圓亭', 'Sernik @ Cukiernia Michałek'],
      backup: [
        {label:'雨天備案', where:'MOCAK 當代藝術博物館', why:'PLN 28，與辛德勒工廠同園區，2 h 室內'},
        {label:'時間吃緊', where:'跳過紡織會館 → 旅館寄行李 → 早 30 分到車站', why:'IC 月台廣，Główny 大廳寄物滿員時可提早入站'},
      ],
      practical: [
        {tag:'寄物', name:'旅館 + Główny locker 雙層保險', note:'退房後優先寄旅館；若旅館不收，車站 locker PLN 9'},
      ],
    },
    {
      n: 5, date: '10/28 (三)', city: '弗羅茨瓦夫 → 波茲南',
      title: '小矮人尋寶 + 點燈儀式 + 晚轉場',
      headline: 'IC 19:00 → 21:20 · 2h20',
      tag: 'Transit',
      weather: '10° / 4°',
      train: {type:'IC', from:'WRO', to:'POZ', dep:'19:00', arr:'21:20', dur:'2h20', price:'PLN 50–90'},
      steps: [
        {t:'09:00', label:'★ 中央廣場 + 紡織會館', sub:'dwarfsmap.com 找小矮人', cost:'免費', dur:'1.5 h'},
        {t:'10:30', label:'糖果屋雙屋 + 教堂塔樓', sub:'91m 全景', cost:'PLN 15', dur:'45 min'},
        {t:'11:30', label:'★ 拉茨瓦夫全景畫', sub:'30 分鐘導覽', cost:'PLN 50', dur:'1 h'},
        {t:'13:30', label:'★ 百年廳 (UNESCO)', sub:'外觀 + 4 圓頂展館', cost:'PLN 30', dur:'1.5 h'},
        {t:'15:50', label:'★ 座堂島煤氣燈', sub:'點燈師 102 盞 · 日落 16:32', cost:'免費', dur:'45 min'},
        {t:'19:00', label:'IC 火車出發', cost:'PLN 50–90', dur:'2h20'},
      ],
      eat: ['Śląskie kluski @ Konspira', 'Browar Stu Mostów 精釀'],
      backup: [
        {label:'雨天備案', where:'SkyTower 49F 觀景台', why:'PLN 22，212m 全城景，雨天最佳室內備案'},
        {label:'點燈師看不到', where:'廣場連拱廊 + 紡織會館內部市集', why:'若 16:32 日落雨遮蔽煤氣燈，回廣場喝熱酒（PLN 12）'},
      ],
    },
    {
      n: 6, date: '10/29 (四)', city: '波茲南 → 華沙',
      title: '山羊鐘樓秀 + 聖馬丁牛角麵包',
      headline: 'EIP 17:30 → 19:50 · 2h20',
      tag: 'Transit',
      weather: '11° / 5°',
      train: {type:'EIP', from:'POZ', to:'WAW', dep:'17:30', arr:'19:50', dur:'2h20', price:'PLN 90–150'},
      steps: [
        {t:'09:00', label:'★ 教堂島 Ostrów Tumski', sub:'梅什科一世受洗地', cost:'PLN 16', dur:'1.5 h'},
        {t:'11:00', label:'廣場卡正面位置', dur:'45 min · 提早卡位'},
        {t:'12:00', label:'★ 山羊鐘樓秀', sub:'每天中午限定', cost:'免費', dur:'5 min'},
        {t:'12:15', label:'★ 聖馬丁牛角麵包 (PGI)', sub:'Cukiernia Kandulski', cost:'PLN 12–18', dur:'15 min'},
        {t:'14:00', label:'帝王城堡 / Stary Browar', cost:'PLN 16', dur:'2 h'},
        {t:'17:30', label:'EIP 出發', cost:'PLN 90–150', dur:'2h20'},
        {t:'19:50', label:'抵華沙中央車站'},
      ],
      eat: ['Rogal Świętomarciński (PGI) ⭐', 'Pyry z gzikiem @ Pyra Bar'],
      backup: [
        {label:'12:00 鐘樓秀濕滑', where:'牛角麵包博物館內現場互動秀', why:'PLN 25 · 室內可看做麵包，比鐘樓秀深度高'},
        {label:'雨天備案', where:'Stary Browar 商場 + 帝王城堡內部', why:'兩處步行 10 分相連，全程室內可消磨 3 h'},
      ],
    },
    {
      n: 7, date: '10/30 (五)', city: '華沙',
      title: 'POLIN + 起義 + 蕭邦音樂會',
      headline: '華沙告別日 · 三大博物館 + 鋼琴獨奏',
      tag: 'Capital',
      weather: '10° / 4°',
      steps: [
        {t:'10:00', label:'★ POLIN 猶太博物館', sub:'線上預約 · 含中文語音', cost:'PLN 45 (週四免費)', dur:'2.5 h'},
        {t:'13:30', label:'午餐 Tel Aviv Urban', cost:'PLN 50–80', dur:'1 h'},
        {t:'14:30', label:'★ 華沙起義博物館', sub:'3D 影院 · 互動區', cost:'PLN 30 (週一/四免費)', dur:'2 h'},
        {t:'17:00', label:'★ 皇家城堡內部', sub:'最後入場 · 林布蘭', cost:'PLN 60 (週三免費)', dur:'1.5 h'},
        {t:'19:00', label:'★ Fryderyk 蕭邦獨奏會', sub:'95–140 PLN · Podwale 13/15', cost:'PLN 95–140', dur:'1 h'},
        {t:'20:00', label:'晚餐 U Fukiera / Polka', cost:'PLN 120–200'},
      ],
      eat: ['Żurek 酸黑麥湯 @ U Fukiera', 'Pączki @ A. Blikle 1869'],
      warn: '蕭邦博物館 2026 全年閉館整修，改聽 Fryderyk Concert Hall 真人獨奏',
      backup: [
        {label:'三館太累', where:'擇 POLIN + 起義 二選一 → 多留 1.5 h 給城堡', why:'POLIN 動線完整需 3 h，起義內容沉重，連看會疲乏'},
        {label:'蕭邦門票售完', where:'Time For Chopin · 老城聖十字教堂', why:'PLN 80 · 1 h 蕭邦心臟所在地，氛圍極佳'},
      ],
    },
    {
      n: 8, date: '10/31 (六)', city: '華沙 → 多哈',
      title: '機場日 · 14:40 QR 260 起飛',
      headline: '從容收尾 · SKM 機場線 20 分鐘',
      tag: 'Departure',
      weather: '9° / 3°',
      steps: [
        {t:'08:00', label:'早餐 + 老城散步', cost:'PLN 40', dur:'1.5 h'},
        {t:'10:30', label:'退房 → Warszawa Centralna', dur:'10 min'},
        {t:'10:40', label:'SKM S2/S3', cost:'PLN 4.4', dur:'20 min'},
        {t:'11:00', label:'抵 Chopin 第一航廈'},
        {t:'11:15', label:'退稅蓋章', sub:'Global Blue / Planet 海關櫃台', dur:'15–30 min'},
        {t:'11:30', label:'報到 + 安檢', dur:'1 h'},
        {t:'14:40', label:'★ QR 260 起飛', sub:'WAW → DOH → HKG → TPE'},
      ],
      backup: [
        {label:'班機提早 2 h', where:'蕭邦機場 1F Costa Coffee · 觀景窗', why:'退稅 + 安檢順可能 12:30 就過關，1F 貴賓區外有平價咖啡'},
        {label:'紀念品最後採買', where:'Wedel + Krówki 機場店', why:'1F 出境前最後一站，伴手禮價差 +10–15% 但方便'},
      ],
    },
  ],
  cities: [
    {key:'WAW', name:'華沙', pl:'Warszawa', tag:'CAPITAL', nights:2, vibe:'鋼鐵摩天 × 重建老城', highlights:['POLIN 猶太博物館','起義博物館','皇家城堡','Krakowskie Przedmieście']},
    {key:'KRK', name:'克拉科夫', pl:'Kraków', tag:'OLD WORLD', nights:3, vibe:'中世紀石板路 × 千年王城', highlights:['Wawel 城堡','中央市集 Rynek','Auschwitz 一日往返','Kazimierz 猶太區']},
    {key:'WRO', name:'弗羅茨瓦夫', pl:'Wrocław', tag:'700 DWARFS', nights:1, vibe:'700 小矮人 × 煤氣燈點燈', highlights:['百年廳 UNESCO','全景畫 Panorama','座堂島 Ostrów Tumski','糖果屋雙屋']},
    {key:'POZ', name:'波茲南', pl:'Poznań', tag:'CRADLE', nights:1, vibe:'波蘭文明發源 × 山羊報時', highlights:['教堂島 Ostrów Tumski','12:00 山羊鐘樓秀','聖馬丁牛角麵包 PGI','帝王城堡']},
  ],
  trains: [
    {seg:'WAW → KRK', date:'10/25', type:'EIP', dep:'09:00', arr:'11:25', dur:'2h25', price:'130–180'},
    {seg:'KRK ⇄ Auschwitz', date:'10/26', type:'BUS', dep:'07:30', arr:'14:30', dur:'1h30 ×2', price:'30'},
    {seg:'KRK → WRO', date:'10/27', type:'IC', dep:'17:30', arr:'21:00', dur:'3h30', price:'60–110'},
    {seg:'WRO → POZ', date:'10/28', type:'IC', dep:'19:00', arr:'21:20', dur:'2h20', price:'50–90'},
    {seg:'POZ → WAW', date:'10/29', type:'EIP', dep:'17:30', arr:'19:50', dur:'2h20', price:'90–150'},
  ],

  flights: {
    out: [
      {code:'CX 479',  leg:'TPE → HKG', when:'10/23 五 21:05 → 23:05', dur:'2h00m'},
      {code:'⇄ HKG',   leg:'轉機',       when:'2h20m', dur:'', layover:true},
      {code:'QR 815',  leg:'HKG → DOH', when:'10/24 六 01:25 → 04:50', dur:'8h25m'},
      {code:'⇄ DOH',   leg:'轉機',       when:'3h40m', dur:'', layover:true},
      {code:'QR 259',  leg:'DOH → WAW', when:'10/24 六 08:30 → 13:30', dur:'6h00m'},
    ],
    back: [
      {code:'QR 260',  leg:'WAW → DOH', when:'10/31 六 14:40 → 22:10', dur:'6h30m'},
      {code:'⇄ DOH',   leg:'轉機',       when:'3h55m', dur:'', layover:true},
      {code:'QR 818',  leg:'DOH → HKG', when:'11/1 日 02:05 → 14:50', dur:'7h45m'},
      {code:'⇄ HKG',   leg:'轉機',       when:'4h50m', dur:'', layover:true},
      {code:'BR 872',  leg:'HKG → TPE', when:'11/1 日 19:40 → 21:25', dur:'1h45m'},
    ],
  },

  stay: [
    {city:'華沙', en:'Warszawa', pick:'Śródmieście Północne / Powiśle', note:'Śródmieście 交通最便利、地鐵 1/2 線交會；老城氣氛佳但晚上冷清；Praga 河東岸藝術替代區。', tip:'兼顧便利與在地感'},
    {city:'克拉科夫', en:'Kraków', pick:'Kazimierz 或 Stradom', note:'老城 5 分鐘步行可達景點但週末喧鬧；Kazimierz 餐酒密集文青氛圍；Podgórze 安靜在地。', tip:'想睡好覺住 Kazimierz；想熱鬧住老城正中'},
    {city:'弗羅茨瓦夫', en:'Wrocław', pick:'Stare Miasto', note:'城本來就不大，住老城最合理。', tip:'老城是首選，無須考慮其他區'},
    {city:'波茲南', en:'Poznań', pick:'Stary Rynek 周邊', note:'廣場周邊步行可達山羊鐘樓秀、教堂島；Stary Browar 商圈消費低。', tip:'四城物價最低'},
  ],

  tickets: [
    {city:'華沙', items:[
      ['皇家城堡', 'PLN 60 · 週三免費'],
      ['POLIN 猶太歷史', 'PLN 45 · 週四免費'],
      ['華沙起義博物館', 'PLN 30 · 週一/週四免費'],
      ['蕭邦博物館', '2026 整年閉館'],
      ['Fryderyk Hall 蕭邦音樂會', 'PLN 95–140'],
      ['科學文化宮觀景台', 'PLN 25'],
    ]},
    {city:'克拉科夫', items:[
      ['瓦維爾城堡套票', 'PLN 45–65'],
      ['辛德勒工廠', 'PLN 38'],
      ['聖瑪麗教堂登塔', 'PLN 20'],
      ['奧斯威辛 Educator 導覽', 'PLN 150'],
      ['維利奇卡鹽礦', 'PLN 159'],
      ['地下市集博物館', 'PLN 32'],
    ]},
    {city:'弗羅茨瓦夫', items:[
      ['百年廳 Hala Stulecia', 'PLN 30'],
      ['拉茨瓦夫全景畫', 'PLN 50'],
    ]},
    {city:'波茲南', items:[
      ['牛角麵包博物館', 'PLN 25'],
      ['帝王城堡', 'PLN 16'],
      ['古市政廳博物館', 'PLN 10'],
    ]},
  ],

  foods: [
    {n:'01', cn:'波蘭餃子', pl:'Pierogi', desc:'國民料理，半月形餃子有鹹甜兩款。最經典 Pierogi Ruskie（馬鈴薯加 twaróg 起司）。'},
    {n:'02', cn:'獵人燉菜', pl:'Bigos', desc:'波蘭國菜。酸菜 + 新鮮高麗菜 + 多種肉長時間慢燉，每位媽媽都有自家配方。'},
    {n:'03', cn:'酸黑麥湯', pl:'Żurek', desc:'發酵黑麥麵粉熬製，配香腸水煮蛋盛在挖空麵包碗，湯喝完碗也吃掉。'},
    {n:'04', cn:'炸豬排', pl:'Kotlet Schabowy', desc:'波蘭家庭週日必備。豬里肌錘薄裹麵包粉炸金黃，配馬鈴薯泥酸菜。'},
    {n:'05', cn:'包心菜捲', pl:'Gołąbki', desc:'意為「小鴿子」。高麗菜葉包米飯絞肉，淋番茄醬汁烘烤。'},
    {n:'06', cn:'波蘭披薩', pl:'Zapiekanka', desc:'長棍麵包剖半鋪蘑菇起司火腿烤製。1970 年代誕生，Plac Nowy 圓亭最有名。'},
    {n:'07', cn:'波蘭甜甜圈', pl:'Pączki', desc:'油炸酵母麵團，玫瑰果醬內餡。Blikle / Stara Pączkarnia 公認最佳。'},
    {n:'08', cn:'起司蛋糕 / 蘋果派', pl:'Sernik / Szarlotka', desc:'Sernik twaróg 起司蛋糕比紐約款輕盈濕潤；Szarlotka 蘋果派配香草冰淇淋。'},
    {n:'09', cn:'圓圈麵包 PGI', pl:'Obwarzanek', desc:'克拉科夫街頭環形麵包，類似貝果但更輕。歐盟地理標誌保護，PLN 3–5。'},
    {n:'10', cn:'煙燻羊乳酪', pl:'Oscypek', desc:'塔特拉山牧羊人手工製作，鹽水浸泡後針葉樹煙燻。可炙烤淋蔓越莓醬。'},
    {n:'11', cn:'馬鈴薯餅', pl:'Placki Ziemniaczane', desc:'馬鈴薯刨絲混蛋液煎成酥脆，配酸奶油或匈牙利風味牛肉燉醬。'},
    {n:'12', cn:'野牛草伏特加', pl:'Żubrówka', desc:'比亞沃韋札森林野牛草浸泡，每瓶都有真草。經典喝法 Tatanka：配蘋果汁。'},
  ],

  cityFood: [
    {city:'華沙', en:'Warszawa', items:[
      {tag:'美食市集', name:'Hala Koszyki', note:'百年美食市集', book:'walk'},
      {tag:'Pierogi', name:'Zapiecek', note:'老城多家分店', book:'walk'},
      {tag:'熱巧克力', name:'E. Wedel Pijalnia', note:'蕭邦曾常去', book:'queue'},
      {tag:'米其林必比登', name:'U Fukiera / Polka', note:'Żurek 麵包碗', book:'must'},
      {tag:'牛奶吧', name:'Bar Prasowy', note:'套餐 PLN 25–35', book:'walk'},
      {tag:'Pączki', name:'A. Blikle', note:'1869 年老字號', book:'queue'},
    ]},
    {city:'克拉科夫', en:'Kraków', items:[
      {tag:'米其林必比登', name:'Starka / Szara Gęś', note:'Kazimierz 與廣場', book:'must'},
      {tag:'地窖晚餐', name:'Pod Aniołami', note:'燭光氛圍', book:'must'},
      {tag:'文青早午餐', name:'Charlotte', note:'Plac Szczepański', book:'queue'},
      {tag:'猶太料理', name:'Hamsa / Klezmer-Hois', note:'Kazimierz', book:'walk'},
      {tag:'Pierogi', name:'Pierogarnia Krakowiacy', note:'老城手工餃子', book:'walk'},
      {tag:'Zapiekanka', name:'Plac Nowy 圓亭', note:'Endzior / Krzysiek', book:'queue'},
      {tag:'米其林一星', name:'Bottiglieria 1881', note:'需提前 2 週訂位', book:'must'},
      {tag:'Sernik', name:'Cukiernia Michałek', note:'百年甜點老店', book:'walk'},
    ]},
    {city:'弗羅茨瓦夫', en:'Wrocław', items:[
      {tag:'西里西亞', name:'Konspira', note:'80 年代反共主題', book:'walk'},
      {tag:'Pierogi', name:'Pierogarnia Stary Młyn', note:'廣場旁', book:'walk'},
      {tag:'融合料理', name:'Karczma Lwowska', note:'波蘭/烏克蘭', book:'walk'},
      {tag:'市場午餐', name:'Hala Targowa', note:'PLN 20–30', book:'walk'},
      {tag:'精釀啤酒', name:'Browar Stu Mostów', note:'旗艦廠', book:'walk'},
      {tag:'米其林必比登', name:'Pod Fredrą / Jadka', note:'廣場旁傳統', book:'must'},
    ]},
    {city:'波茲南', en:'Poznań', items:[
      {tag:'Lech 啤酒', name:'Stary Browar', note:'古釀酒廠改造', book:'walk'},
      {tag:'燒烤', name:'Whiskey In The Jar', note:'燒烤名店', book:'must'},
      {tag:'PGI 牛角', name:'Cukiernia Kandulski', note:'百年老店', book:'queue'},
      {tag:'家常', name:'Pyra Bar', note:'馬鈴薯佐凝乳', book:'walk'},
      {tag:'歷史名宅', name:'Hotel Bazar', note:'蕭邦曾下榻', book:'walk'},
      {tag:'重口味', name:'Stary Maglownik', note:'鴨血酸湯', book:'walk'},
    ]},
  ],

  safety: {
    emergency: [
      ['歐洲通用緊急', '112'],
      ['警察 Policja', '997'],
      ['消防 Straż Pożarna', '998'],
      ['救護 Pogotowie', '999'],
      ['市政警察', '986'],
    ],
    embassy: [
      ['駐波蘭台北代表處', 'Al. Jerozolimskie 179, Warszawa'],
      ['辦公室電話', '+48 22 213 0060'],
      ['急難救助專線', '+48 668 027 574'],
      ['外交部 24h 專線', '+886 800 085 095'],
    ],
    tips: [
      {label:'觀光陷阱', text:'廣場「免費試衣」拍照後索費；中央車站黑計程車（堅持 Bolt / Uber）；市中心換匯陷阱（Kantor 買賣價差 ≤ 1.5%）'},
      {label:'禮儀', text:'進教堂脫帽；Auschwitz 禁笑鬧自拍；勿把波蘭當俄國；餐廳小費約 10%'},
      {label:'治安', text:'全球安全指數前 30。注意觀光區扒手（火車站、Rynek）；貴重物品用前背包'},
      {label:'就醫', text:'自來水可生飲；Apteka 藥局普及；建議投保涵蓋緊急醫療的旅平險'},
    ],
  },

  practical: [
    {tag:'左行寄物', name:'火車站 Locker', note:'WAW Centralna / KRK Główny / WRO Główny / POZ Główny 都有自助 locker。小箱 PLN 8–12 / 大箱 PLN 12–18 · 24 h 為一單位。'},
    {tag:'換錢', name:'Kantor 民間匯兌', note:'機場 / 觀光區匯率最差。市區「Internet Kantor」、「Kantor Pomocna」買賣價差 ≤ 1.5%。⚠ 看到「0% Commission」要警覺。'},
    {tag:'SIM 卡', name:'Play / Plus / Orange', note:'蕭邦機場到達層櫃台、市區 Empik / Żabka 都有。PLN 30 起含 30 天無限上網 + 通話。台灣免簽歐盟漫遊不適用波蘭費率。'},
    {tag:'付款', name:'信用卡 + Revolut', note:'四城 95% 商家收 Visa / Master，含廣場攤販。Apple Pay 普及。建議帶 PLN 200–300 現金應付小費 / 教堂 / 鄉間。'},
    {tag:'退稅', name:'Tax Free 海關蓋章', note:'單筆 PLN 200 以上於 Tax Free 標誌商店可退 8–18% VAT。離境前在蕭邦機場 / KRK 機場海關櫃台蓋章再投退稅信箱。'},
    {tag:'交通卡', name:'單程票 vs 24h 票', note:'華沙 / 克拉科夫 24 h 票約 PLN 18，當日搭 3 趟以上划算。Jakdojade / Koleo App 查時刻 + 直接買票。'},
  ],
  reservations: [
    {when:'出發前 60+ 天', what:'機票 + 各城火車（intercity.pl Super Promo 提前 30 天 5 折）'},
    {when:'出發前 21 天', what:'Auschwitz 英文官方導覽（visit.auschwitz.org · 旺季 14 天前售完）'},
    {when:'出發前 14 天', what:'POLIN 猶太博物館 + 華沙起義博物館 + 辛德勒工廠（mhk.pl/en）'},
    {when:'出發前 7 天', what:'米其林餐廳：Bottiglieria 1881、U Fukiera、Pod Aniołami、Pod Fredrą（TheFork / OpenTable / 餐廳官網）'},
    {when:'出發前 3 天', what:'Fryderyk Hall 蕭邦獨奏會（chopinconcerts.pl · Podwale 13/15 票常於前一週售罄）'},
    {when:'抵達當日', what:'隔日 Wawel 國家廳室現場票（限額制，售完只能改廷院）'},
  ],

  shopping: [
    {tag:'陶瓷', name:'Bolesławiec', note:'藍底白點手繪餐具，全球收藏家追捧'},
    {tag:'琥珀', name:'格但斯克琥珀', note:'辨真偽：泡鹽水會浮、靜電可吸紙屑'},
    {tag:'伏特加', name:'Żubrówka / Soplica', note:'野牛草 / 果味，伴手首選'},
    {tag:'巧克力', name:'E. Wedel', note:'1851 年華沙百年品牌'},
    {tag:'糖果', name:'Krówki', note:'波蘭奶油糖，超市到處有'},
    {tag:'剪紙', name:'Wycinanki', note:'庫亞瓦、洛維奇地區傳統'},
    {tag:'起司', name:'Oscypek', note:'扎科帕內當地產，可帶上飛機'},
  ],

  phrases: [
    ['你好（非正式）', 'Cześć', 'chesh-ch'],
    ['您好', 'Dzień dobry', 'jen dob-ri'],
    ['晚安', 'Dobranoc', 'do-bra-nots'],
    ['謝謝', 'Dziękuję', 'jen-koo-yeh'],
    ['請 / 不客氣', 'Proszę', 'pro-sheh'],
    ['是 / 否', 'Tak / Nie', ''],
    ['對不起', 'Przepraszam', 'psheh-pra-sham'],
    ['廁所在哪', 'Gdzie jest toaleta?', ''],
    ['買單', 'Rachunek proszę', ''],
    ['多少錢', 'Ile to kosztuje?', ''],
    ['乾杯', 'Na zdrowie!', 'naz-dro-vyeh'],
    ['真好吃', 'Smaczne!', 'smach-neh'],
  ],

  about: [
    ['語言', '波蘭語（觀光區英語通）'],
    ['電壓', '230V · C/E/F 型插座'],
    ['時區', 'CET（夏令 CEST）'],
    ['台幣換算', '1 PLN ≈ 8 TWD'],
    ['物價水位', '西歐之 50–60%'],
    ['小費文化', '餐廳 10%（非強制）'],
    ['台灣簽證', '免申根簽 90 天'],
    ['ETIAS', '2026 Q4 起須申請'],
  ],

  cost: [
    ['國際機票', '50,000 – 65,000'],
    ['7 晚住宿（雙人房一半）', '22,000 – 32,000'],
    ['5 段跨城火車', '1,800 – 3,500'],
    ['Auschwitz 一日往返', '1,650'],
    ['主要景點門票', '2,300 – 3,000'],
    ['蕭邦真人鋼琴音樂會', '800 – 1,150'],
    ['城內交通 + Bolt', '1,500 – 2,000'],
    ['餐飲 8 天', '8,000 – 14,000'],
    ['電信 SIM', '350 – 600'],
    ['旅平險 + 不便險', '1,500 – 2,500'],
    ['緩衝預備金', '5,000'],
  ],
};
